[package]
name = "livesplit-core"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
chrono = "0.2.25"
odds = "0.2.25"
serde_json = "0.9.4"
serde_derive = "0.9.5"
serde = "0.9.5"
sxd-document = "0.2.0"
quick-error = "1.1.0"
base64 = "0.3.0"
byteorder = "1.0.0"
image = "0.12.1"
derive_more = "0.5.0"
derive-new = "0.3.0"
