[package]
name = "livesplit-core"
version = "0.8.1"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
documentation = "https://docs.rs/livesplit-core/"
repository = "https://github.com/CryZe/livesplit-core"
license = "Apache-2.0/MIT"
description = "livesplit-core is a library that provides a lot of functionality for creating a speedrun timer."
readme = "README.md"
keywords = ["speedrun", "timer", "livesplit"]
include = [
    "src/*",
    "Cargo.toml",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "CODE_OF_CONDUCT.md",
    "README.md"
]

[badges]
travis-ci = { repository = "CryZe/livesplit-core" }
appveyor = { repository = "CryZe/livesplit-core" }

[profile.release]
lto = true
panic = "abort"

[workspace]
members = ["capi", "capi/bind_gen", "js"]

[[bench]]
name = "balanced_pb"

[[bench]]
name = "parsing"

[dependencies]
base64 = "0.9.0"
byteorder = "1.2.1"
chrono = { version = "0.4.0", features = ["serde"] }
derive_more = "0.7.0"
image = "0.18.0"
livesplit-hotkey = { path = "hotkey", version = "0.2.1" }
odds = { version = "0.3.1", features = ["std-vec"] }
ordered-float = "0.5.0"
ordermap = "0.3.2"
palette = "0.2.1"
parking_lot = "0.5.3"
quick-error = "1.2.0"
quick-xml = "0.10.1"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
unicase = "2.1.0"
