[package]
name = "livesplit-core"
version = "0.1.3"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
documentation = "https://docs.rs/livesplit-core/"
repository = "https://github.com/CryZe/livesplit-core"
license = "Apache-2.0/MIT"
description = "livesplit-core is a library that provides a lot of functionality for creating a speedrun timer."
readme = "README.md"
keywords = ["speedrun", "timer", "livesplit"]
exclude = ["ci/*", "capi/*", "js/*"]

[workspace]
members = ["capi", "capi/bind_gen"]

[dependencies]
chrono = { version = "0.3.0", features = ["serde"] }
odds = "0.2.25"
serde_json = "0.9.8"
serde_derive = "0.9.9"
serde = "0.9.9"
sxd-document = "0.2.0"
quick-error = "1.1.0"
base64 = "0.4.0"
byteorder = "1.0.0"
image = "0.12.3"
derive_more = "0.6.0"
derive-new = "0.4.0"
pdqsort = "0.1.2"
