[package]
name = "livesplit-core"
version = "0.4.1"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
documentation = "https://docs.rs/livesplit-core/"
repository = "https://github.com/CryZe/livesplit-core"
license = "Apache-2.0/MIT"
description = "livesplit-core is a library that provides a lot of functionality for creating a speedrun timer."
readme = "README.md"
keywords = ["speedrun", "timer", "livesplit"]
exclude = ["ci/*", "capi/*", "js/*", "hotkey/*"]

[profile.release]
lto = true
panic = "abort"

[workspace]
members = ["capi", "capi/bind_gen", "js"]

[dependencies]
chrono = { version = "0.3.0", features = ["serde"] }
odds = "0.2.25"
serde_json = "1.0.1"
serde_derive = "1.0.2"
serde = "1.0.2"
sxd-document = "0.2.0"
quick-error = "1.2.0"
base64 = "0.5.2"
byteorder = "1.0.0"
image = "0.13.0"
derive_more = "0.6.0"
derive-new = "0.4.0"
pdqsort = "1.0.3"
livesplit-hotkey = { path = "hotkey", version = "0.2.0" }
