[package]
name = "livesplit-core-capi"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
livesplit-core = { path = ".." }
libc = "0.2.18"

[[bin]]
name = "livesplit_core"
path = "src/bin/emscripten.rs"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
