[package]
name = "livesplit-core-capi"
version = "0.1.2"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
livesplit-core = { path = ".." }
libc = "0.2.18"

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.release]
panic = 'abort'
