[package]
name = "livesplit-core-capi"
version = "0.5.1"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
livesplit-core = { path = ".." }
libc = "0.2.18"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
