[package]
name = "livesplit-auto-splitting"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.45"
log = "0.4.14"
proc-maps = "0.2.0"
read-process-memory = "0.1.4"
slotmap = "1.0.2"
snafu = "0.6.10"
sysinfo = "0.22.4"
time = "0.3.3"
wasmtime = { version = "0.32.0", default-features = false, features = [
  "cranelift",
] }
