name: Benchmarking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run benchmarks
    runs-on: ubuntu-latest
    env:
      CRITERION_TOKEN: ${{ secrets.CRITERION_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run benchmarks
        run: |
          # run benchmarks and save baseline to "criterion.dev.temp"
          cargo bench --all-features -- --verbose --noplot --save-baseline criterion.dev.temp
          # set the path to the file to upload to criterion.dev
          echo "::set-env name=CRITERION_FILE_PATH::$(find ./target/criterion/ -name raw.csv)"

      - name: Upload benchmarks
        run: |
          # upload the file
          curl -F 'raw.csv=@${{ env.CRITERION_FILE_PATH }}' \
          'https://api.criterion.dev/v1/${{ github.repository }}/measurements?token=${{ secrets.CRITERION_TOKEN }}&commit=${{ github.sha }}'
